import { oc } from "@orpc/contract";
import { ErrorValue, SpaceProps, SuccessValue } from "@/types";

/**
 * Contract for creating a new space.
 * - pass 'parentSpaceId' to create a sub-space within a parent space
 * - id is generated by the client & should never change (ideally)
 */
export const createSpace = oc
  .route({
    method: "POST",
    path: "/space/{id}",
    summary: "Create a new space",
  })
  .input(SpaceProps.partial())
  .output(SuccessValue(SpaceProps.pick("id")).or(ErrorValue));
